# Site settings
title: Eddie Smolyansky blog
email: 
description: "Enjoying life through a rational lens."
# baseurl: ""
url: "https://eddiesmo.github.io"
# twitter_username: karpathy
github_username:  eddiesmo

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
